src/main/java/at/synaptos/synapphys/model/BillingItem.java
package at.synaptos.synapphys.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

@Table(name = "billing_item")
@Entity
public class BillingItem implements Serializable {

	private static final long serialVersionUID = -7832487719362633662L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "billing_item_id")
	private Long id;

	@NotNull
	private String subject;

	@NotNull
	private Integer quantity;

	@NotNull
	@Column(name = "amount")
	private BigDecimal amount;

	@Column(name = "vat")
	private BigDecimal vat;

	@NotNull
	@Column(name = "sequence_no")
	private Integer sequenceNo;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "service_date")
	private Date serviceDate;

	@ManyToOne
	@JoinColumn(name = "service_documentation", referencedColumnName = "service_documentation_id")
	private ServiceDocumentation serviceDocumentation;

	@NotNull
	@ManyToOne
	@JoinColumn(name = "billing", referencedColumnName = "billing_id", nullable = false)
	private Billing billing;

	public BillingItem() {
		setQuantity(1);
		setAmount(BigDecimal.ZERO);
	}

	public static BillingItem getInstance() {
		final BillingItem instance = new BillingItem();
		return instance;
	}

	public static BillingItem getInstance(@NotNull final ServiceDocumentation serviceDocumentation) {
		final BillingItem instance = getInstance();
		instance.setSubject(serviceDocumentation.getServiceType().getName());
		instance.setAmount(serviceDocumentation.getServiceType().getAmount());
		instance.setQuantity(serviceDocumentation.getQuantity());
		instance.setServiceDate((Date) serviceDocumentation.getSessionDocumentation().getStartDate().clone());
		instance.setServiceDocumentation(serviceDocumentation);
		return instance;
	}

	@PrePersist
	private void prePersist() {
		if (getQuantity() == null) {
			setQuantity(1);
		}
		if (getAmount() == null) {
			setAmount(BigDecimal.ZERO);
		}
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getAmount() {
		return amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public BigDecimal getVat() {
		return vat;
	}

	public void setVat(BigDecimal vat) {
		this.vat = vat;
	}

	public Integer getSequenceNo() {
		return sequenceNo;
	}

	public void setSequenceNo(Integer sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	public Date getServiceDate() {
		return serviceDate;
	}

	public void setServiceDate(Date serviceDate) {
		this.serviceDate = serviceDate;
	}

	public BillingItem withServiceDate(Date serviceDate) {
		setServiceDate(serviceDate);
		return this;
	}

	public ServiceDocumentation getServiceDocumentation() {
		return serviceDocumentation;
	}

	public void setServiceDocumentation(ServiceDocumentation serviceDocumentation) {
		this.serviceDocumentation = serviceDocumentation;
	}

	public BillingItem withServiceDocumentation(ServiceDocumentation serviceDocumentation) {
		setServiceDocumentation(serviceDocumentation);
		return this;
	}

	public Billing getBilling() {
		return billing;
	}

	public void setBilling(Billing billing) {
		this.billing = billing;
	}

	@Override
	public int hashCode() {
		return (id != null) ? this.getClass().hashCode() + id.hashCode() : super.hashCode();
	}

	@Override
	public boolean equals(Object other) {
		return (other instanceof BillingItem && id != null) ? id.equals(((BillingItem) other).id) : (other == this);
	}

	@Override
	public String toString() {
		return this.getClass().getName() + "{id=" + id + ", subject=" + subject + ", quantity=" + quantity + ", amount="
				+ amount + ", vat=" + vat + ", sequenceNo=" + sequenceNo + ", serviceDate=" + serviceDate
				+ ", serviceDocumentation=" + serviceDocumentation + ", billing=" + billing + "}";
	}

	public boolean isNew() {
		return id == null;
	}

	public double getTotal() {
		BigDecimal vat = getVat() == null ? BigDecimal.ZERO : getVat();
		return getAmount().multiply(BigDecimal.valueOf(getQuantity()))
				.multiply(BigDecimal.valueOf(100).add(vat).divide(BigDecimal.valueOf(100))).doubleValue();
	}

}

src/main/java/at/synaptos/synapphys/model/BillingType.java
package at.synaptos.synapphys.model;

public enum BillingType {
    RECEIPT,
    INVOICE
}

src/main/java/at/synaptos/synapphys/model/ScheduleItem.java
package at.synaptos.synapphys.model;

import java.time.LocalDateTime;
import java.util.Date;
import java.util.Optional;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import at.synaptos.synapphys.utils.DateUtils;

@NamedQueries({
		@NamedQuery(name = ScheduleItem.FIND_ALL, query = "select i from ScheduleItem i where i.deletedDate is null"),
		@NamedQuery(name = ScheduleItem.FIND_BETWEEN, query = "select i from ScheduleItem i where i.startDate <= :endDate and i.endDate >= :startDate and"
				+ " i.deletedDate is null order by i.startDate") })
@Table(name = "schedule_item", indexes = { @Index(columnList = "schedule_start_date, schedule_end_date") })
@Entity
public class ScheduleItem extends AbstractEntity {

	private static final long serialVersionUID = -1700451807673251684L;

	public static final String FIND_ALL = "ScheduleItem.findAll";
	public static final String FIND_BETWEEN = "ScheduleItem.findBetween";

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "schedule_item_id")
	private Long id;

	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "schedule_start_date")
	private Date startDate;

	@NotNull
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "schedule_end_date")
	private Date endDate;

	@Column(name = "schedule_subject")
	private String subject;

	@Column(name = "schedule_note")
	private String note;

	@Column(name = "phone")
	private String phone;

	@Column(name = "remind_by_sms")
	private Boolean remindBySms;

	@Column(name = "confirmed_date")
	private Date confirmedDate;

	@ManyToOne
	@JoinColumn(name = "client", referencedColumnName = "person_id")
	private Client client;

	public ScheduleItem() {
		setRemindBySms(false);
	}

	public static ScheduleItem getInstance() {
		return new ScheduleItem();
	}

	public static ScheduleItem getInstance(@NotNull final Date startDate, @NotNull final Date endDate) {
		return getInstance().withStartDate(startDate).withEndDate(endDate);
	}

	public static ScheduleItem getInstance(@NotNull final LocalDateTime startLdt, @NotNull final LocalDateTime endLdt) {
		return getInstance().withStartLdt(startLdt).withEndLdt(endLdt);
	}

	@PrePersist
	public void prePersist() {
		if (getRemindBySms() == null) {
			setRemindBySms(false);
		}
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getStartDate() {
		return startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = Optional.ofNullable(startDate).orElseGet(() -> (Date) startDate.clone());
	}

	public ScheduleItem withStartDate(Date startDate) {
		setStartDate(startDate);
		return this;
	}

	public LocalDateTime getStartLdt() {
		return DateUtils.asLdt(getStartDate());
	}

	public void setStartLdt(LocalDateTime startLdt) {
		setStartDate(DateUtils.asDate(startLdt));
	}

	public ScheduleItem withStartLdt(LocalDateTime startLdt) {
		setStartDate(DateUtils.asDate(startLdt));
		return this;
	}

	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = Optional.ofNullable(endDate).orElseGet(() -> (Date) endDate.clone());
	}

	public ScheduleItem withEndDate(Date endDate) {
		setEndDate(endDate);
		return this;
	}

	public LocalDateTime getEndLdt() {
		return DateUtils.asLdt(getEndDate());
	}

	public void setEndLdt(LocalDateTime endLdt) {
		setEndDate(DateUtils.asDate(endLdt));
	}

	public ScheduleItem withEndLdt(LocalDateTime endLdt) {
		setEndDate(DateUtils.asDate(endLdt));
		return this;
	}

	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Boolean getRemindBySms() {
		return remindBySms;
	}

	public Boolean isRemindBySms() {
		return getRemindBySms();
	}

	public void setRemindBySms(Boolean remindBySms) {
		this.remindBySms = remindBySms;
	}

	public ScheduleItem withRemindBySms(Boolean remindBySms) {
		setRemindBySms(remindBySms);
		return this;
	}

	public Date getConfirmedDate() {
		return confirmedDate;
	}

	public void setConfirmedDate(Date confirmedDate) {
		this.confirmedDate = confirmedDate;
	}

	public ScheduleItem withConfirmedDate(Date confirmedDate) {
		setConfirmedDate(confirmedDate);
		return this;
	}

	public LocalDateTime getConfirmedLdt() {
		return DateUtils.asLdt(getConfirmedDate());
	}

	public void setConfirmedLdt(LocalDateTime confirmedLdt) {
		setConfirmedDate(DateUtils.asDate(confirmedLdt));
	}

	public ScheduleItem withConfirmedLdt(LocalDateTime confirmedLdt) {
		setConfirmedLdt(confirmedLdt);
		return this;
	}

	public Client getClient() {
		return client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public ScheduleItem withClient(Client client) {
		setClient(client);
		return this;
	}

	@Override
	public int hashCode() {
		return (id != null) ? this.getClass().hashCode() + id.hashCode() : super.hashCode();
	}

	@Override
	public boolean equals(Object other) {
		return (other instanceof ScheduleItem && id != null) ? id.equals(((ScheduleItem) other).id) : (other == this);
	}

	@Override
	public String toString() {
		return this.getClass().getName() + "{id=" + id + ",startDate=" + startDate + ",endDate=" + endDate + ",subject="
				+ subject + ",note=" + note + ",phone=" + phone + ",note=" + note + ",remindBySms=" + remindBySms
				+ ",confirmedDate=" + confirmedDate + ",client=" + client + "}";
	}

	@Override
	public boolean isNew() {
		return id == null;
	}

	@Override
	public boolean isDeleted() {
		return super.isDeleted() && getConfirmedDate() != null;
	}

}

src/main/webapp/pages/billing/billingList.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:of="http://omnifaces.org/functions"
	xmlns:p="http://primefaces.org/ui"
	xmlns:sc="http://java.sun.com/jsf/composite/cc/crud">

	<div class="layout-main-content">
		<div class="ui-g ui-fluid">
			<div class="ui-g-12">
				<div class="card">
					<h:form>
						<p:dataTable widgetVar="billings"
							value="#{billingListController.billings}" var="billing"
							rowKey="#{billing.id}" sortBy="#{billing.billingDate}"
							sortOrder="descending"
							emptyMessage="#{i18n['emptyMessage.text']}" reflow="true"
							filteredValue="#{billingListController.filteredBillings}">
							<f:facet name="header">
								<p:panelGrid columns="4" layout="grid"
									styleClass="ui-panelgrid-blank"
									columnClasses="ui-grid-col-1 TexAlLeft,ui-grid-col-5,
										ui-grid-col-5,ui-grid-col-1">
									<h:outputText styleClass="#{TagAttribute.ICON_BILLING} Fs20" />
									<h:outputText
										value="#{i18n[billingListController.textKeyForBillingType('s.label')]}"
										styleClass="Fs20" />
									<p:panelGrid columns="3" layout="grid"
										styleClass="ui-panelgrid-blank">
										<p:commandButton id="billingDateDecr"
											icon="fa fa-chevron-left" process="@this"
											update="@widgetVar(billings)"
											actionListener="#{billingListController.doBillingDateDecr}" />

										<p:outputPanel style="padding-top: 10px">
											<h:outputText
												value="#{billingListController.filteredStartDate}"
												styleClass="TexAlCenter" style="font-weight: bold">
												<f:convertDateTime type="date" pattern="MMMM yy" />
											</h:outputText>
										</p:outputPanel>

										<p:commandButton id="billingDateIncr"
											icon="fa fa-chevron-right" process="@this"
											update="@widgetVar(billings)"
											actionListener="#{billingListController.doBillingDateIncr}" />
									</p:panelGrid>
								</p:panelGrid>
							</f:facet>

							<p:column headerText="#{i18n['billing.billingDate.label']}"
								sortBy="#{billing.billingDate}">
								<p:outputPanel
									styleClass="#{billing.deleted ? 'LineThrough' : ''}"
									style="text-align: center">
									<h:outputText value="#{billing.billingDate}">
										<f:convertDateTime dateStyle="short" type="date" />
									</h:outputText>
								</p:outputPanel>
							</p:column>

							<p:column
								headerText="#{i18n[billingListController.textKeyForBillingType('.referenceNo.label')]}">
								<p:outputPanel
									styleClass="#{billing.deleted ? 'LineThrough' : ''}"
									style="text-align: center">
									<h:outputText value="#{billing.referenceNo}" />
								</p:outputPanel>
							</p:column>

							<p:column headerText="#{publicViewController.currencySymbol}">
								<p:outputPanel
									styleClass="#{billing.deleted ? 'LineThrough' : ''}"
									style="text-align: right">
									<h:outputText
										value="#{of:formatNumber(billing.total,'#,##0.00')}" />
								</p:outputPanel>
							</p:column>

							<p:column headerText="#{i18n['billing.paymentMethod.label']}"
								rendered="#{billingListController.billingType != BillingType.INVOICE}">
								<p:outputPanel
									styleClass="#{billing.deleted ? 'LineThrough' : ''}"
									style="text-align: center">
									<h:outputText value="#{i18n['paymentMethod.range.CASH.name']}"
										rendered="#{billing.paymentMethod == PaymentMethod.CASH}" />
									<h:outputText value="#{i18n['paymentMethod.range.MC.name']}"
										rendered="#{billing.paymentMethod == PaymentMethod.MC}" />
									<h:outputText value="#{i18n['paymentMethod.range.CC.name']}"
										rendered="#{billing.paymentMethod == PaymentMethod.CC}" />
								</p:outputPanel>
							</p:column>

							<p:column headerText="#{i18n['client.label']}" styleClass="Wid10"
								rendered="#{billingListController.billingType == BillingType.INVOICE}">
								<p:outputPanel
									styleClass="#{billing.deleted ? 'LineThrough' : ''}">
									<h:outputText
										value="#{billing.seriesDocumentation.client.fullname}" />
								</p:outputPanel>
							</p:column>

							<p:column headerText="#{i18n['billing.billingNote.label']}">
								<p:outputPanel
									styleClass="#{billing.deleted ? 'LineThrough' : ''}">
									<h:outputText value="#{billing.billingNote}" escape="false" />
								</p:outputPanel>
							</p:column>

							<p:column headerText="#{i18n['billing.dueDate.label']}"
								styleClass="TexAlCenter"
								rendered="#{billingListController.billingType == BillingType.INVOICE}">
								<p:outputPanel
									styleClass="#{billing.deleted ? 'LineThrough' : ''}">
									<h:outputText value="#{billing.dueDate}">
										<f:convertDateTime type="date" dateStyle="short" />
									</h:outputText>
								</p:outputPanel>
							</p:column>

							<p:column headerText="#{i18n['billing.paymentDate.label']}"
								styleClass="TexAlCenter"
								rendered="#{billingListController.billingType == BillingType.INVOICE}">
								<p:outputPanel
									styleClass="#{billing.deleted ? 'LineThrough' : ''}">
									<h:outputText value="#{billing.paymentDate}">
										<f:convertDateTime type="date" dateStyle="short" />
									</h:outputText>
								</p:outputPanel>
							</p:column>

							<p:column headerText="Status" styleClass="TexAlCenter"
								filterBy="#{billing.billingStatus}" filterMatchMode="equals"
								rendered="#{billingListController.billingType == BillingType.INVOICE}">
								<f:facet name="filter">
									<p:selectOneButton styleClass="billingStatusFilter"
										onchange="PF('billings').filter()"
										converter="billingStatusConverter">
										<f:selectItem itemLabel="" itemValue="" />
										<f:selectItem itemLabel="" itemValue="#{BillingStatus.OPEN}" />
										<f:selectItem itemLabel="" itemValue="#{BillingStatus.PAID}" />
										<f:selectItem itemLabel=""
											itemValue="#{BillingStatus.CANCELED}" />
									</p:selectOneButton>
								</f:facet>
								<h:outputText
									styleClass="fa fa-flag Fs20 #{billing.billingStatus.flagStyleClass}" />
							</p:column>

							<p:column styleClass="Wid10">
								<p:panelGrid columns="2" layout="grid"
									styleClass="ui-panelgrid-blank">
									<p:commandButton icon="#{TagAttribute.ICON_DELETE}"
										styleClass="gray-btn" disabled="#{billing.deleted}"
										process="@this" update="@widgetVar(billings)"
										actionListener="#{billingListController.doCancel(billing)}">
										<p:confirm icon="ui-icon-alert"
											header="#{i18n['itemAction.delete.CONFIRM.header']}"
											message="#{i18n['itemAction.delete.CONFIRM.text']}" />
									</p:commandButton>

									<p:commandButton icon="#{TagAttribute.ICON_EDIT}"
										styleClass="gray-btn" disabled="#{billing.deleted}"
										process="@this"
										update="@widgetVar(billingPaymentDateEdit):billingPaymentDateGrid"
										actionListener="#{billingListController.doSelect(billing)}"
										oncomplete="PF('billingPaymentDateEdit').show()" />

									<p:commandButton icon="#{TagAttribute.ICON_PRINT}"
										styleClass="gray-btn" disabled="#{billing.deleted}"
										process="@this" update="@(.billingReceiptPrint)"
										actionListener="#{billingListController.doPrint(billing)}"
										onstart="onStartBillingReceiptPrint"
										oncomplete="onCompleteBillingReceiptPrint(xhr,status,args)" />

									<p:outputPanel />
								</p:panelGrid>
							</p:column>
						</p:dataTable>

						<p:dialog widgetVar="billingPaymentDateEdit" showHeader="false"
							modal="true" draggable="false" resizable="false"
							responsive="true" positionType="absolute" position="center,top">
							<p:outputPanel style="padding: 12px">
								<p:panelGrid id="billingPaymentDateGrid" columns="1"
									layout="grid" styleClass="ui-panelgrid-blank">
									<p:outputLabel for="billingPaymentDate"
										value="#{i18n['billing.paymentDate.label']}" />
									<p:calendar id="billingPaymentDate"
										value="#{selectedBilling.paymentDate}" mode="inline" />
								</p:panelGrid>
							</p:outputPanel>

							<f:facet name="footer">
								<p:panelGrid columns="1" layout="grid"
									styleClass="ui-panelgrid-blank">
									<p:commandButton icon="#{TagAttribute.ICON_SAVE}"
										value="#{i18n['action.save.name']}"
										update="@widgetVar(billings)"
										actionListener="#{billingListController.doSave}"
										oncomplete="PF('billingPaymentDateEdit').hide()" />
									<p:commandButton icon="#{TagAttribute.ICON_BACK}"
										value="#{i18n['action.cancel.name']}" type="button"
										onclick="PF('billingPaymentDateEdit').hide()" />
								</p:panelGrid>
							</f:facet>
						</p:dialog>
					</h:form>
				</div>
			</div>
		</div>
	</div>

	<ui:include
		src="#{billingListController.textKeyForBillingType('','Print.xhtml')}" />

	<sc:editConfirmDialog />

	<h:outputScript>
        //<![CDATA[
        $(function() {
            $('.billingStatusFilter div:nth-child(1) span').addClass('fa fa-asterisk black');
            $('.billingStatusFilter div:nth-child(2) span').addClass('fa fa-flag green');
            $('.billingStatusFilter div:nth-child(3) span').addClass('fa fa-flag blue');
            $('.billingStatusFilter div:nth-child(4) span').addClass('fa fa-flag blueGray');
        })
        //]]>
	</h:outputScript>

</ui:composition>

src/main/webapp/pages/billing/billingNote.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:c="http://java.sun.com/jstl/core"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">

	<p:dialog widgetVar="billingNote" showHeader="false" modal="true"
		draggable="false" resizable="false" responsive="true" visible="false">
		<p:outputPanel style="padding: 4px 8px">
			<p:panelGrid columns="1" layout="grid"
				styleClass="ui-panelgrid-blank" columnClasses="TexAlCenter">
				<p:textEditor widgetVar="billingNoteEdit"
					value="#{billingViewController.preparedBilling.billingNote}"
					maxlength="2000">
					<f:facet name="toolbar">
						<span class="ql-formats">
							<button class="ql-bold"></button>
							<button class="ql-italic"></button>
							<button class="ql-underline"></button>
							<button class="ql-strike"></button>
						</span>
						<span class="ql-formats"> <select class="ql-color"></select>
							<select class="ql-background"></select>
						</span>
						<span class="ql-formats">
							<button class="ql-script" value="sub"></button>
							<button class="ql-script" value="super"></button>
						</span>
						<span class="ql-formats">
							<button class="ql-list" value="ordered"></button>
							<button class="ql-list" value="bullet"></button>
							<button class="ql-indent" value="-1"></button>
							<button class="ql-indent" value="+1"></button>
						</span>
						<span class="ql-formats"> <p:button
								icon="fa fa-undo TexColor"
								onclick="PF('billingNoteEdit').undo(); return false" /> <p:button
								icon="fa fa-repeat TexColor"
								onclick="PF('billingNoteEdit').redo(); return false" />
						</span>
						<span class="ql-formats">
							<button class="ql-clean"></button>
						</span>
					</f:facet>
				</p:textEditor>
			</p:panelGrid>
		</p:outputPanel>

		<f:facet name="footer">
			<p:panelGrid columns="2" layout="grid"
				styleClass="ui-panelgrid-blank">
				<p:commandButton icon="#{TagAttribute.ICON_SAVE}"
					value="#{i18n['action.save.name']}" process="@form"
					update="noteInput" onclick="PF('billingNote').hide()">
				</p:commandButton>
				<p:commandButton value="#{i18n['action.cancel.name']}" 
					icon="#{TagAttribute.ICON_CANCEL}" process="@this"
					onclick="PF('billingNote').hide()">
				</p:commandButton>
			</p:panelGrid>
		</f:facet>
	</p:dialog>

</ui:composition>

src/main/webapp/pages/billing/billingPdf.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"	
	xmlns:p="http://primefaces.org/ui">

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Synaptos Smart Therapy Barbeleg</title>
	</head>

	<h:body>
		<p>
			DAS IST EIN TEST!!!
		</p>
		
		<p>
			Der Beleg ist nicht vollständig, sondern zeigt NUR das Konzept!
		</p>
		
		<h:outputText value="#{usermetaContext.billingCompany}"
			styleClass="Fs20" />
			
		<p:outputPanel
		 	rendered="#{not empty selectedBilling}">
			<p:panelGrid columns="3"
				styleClass="ui-panelgrid-blank Wid100"
				columnClasses="TexAlLeft,TexAlCenter,TexAlRight">
				<p:outputPanel style="padding-left: 6px">
					<h:outputText
						value="#{i18n['billing.receipt.referenceNo.label']}:&#160;"
						styleClass="Fs16" />
					<h:outputText value="#{selectedBilling.referenceNo}"
						styleClass="Fs16 " />
				</p:outputPanel>

				<p:outputPanel>
					<h:outputText value="BARBELEG" styleClass="Fs24" />
				</p:outputPanel>

				<p:outputPanel style="padding-right: 6px">
					<h:outputText
						value="#{i18n['billing.billingDateDay.label']}:&#160;"
						styleClass="Fs16" />
					<h:outputText value="#{selectedBilling.billingDate}"
						styleClass="Fs16">
						<f:convertDateTime dateStyle="short" type="date" />
					</h:outputText>
				</p:outputPanel>
			</p:panelGrid>
		</p:outputPanel>
	</h:body>

</html>

src/main/webapp/pages/billing/invoiceList.xhtml
<ui:composition 
	xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"	
	xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    template="/templates/default.xhtml">

	<ui:define name="title">
		<h:outputText value="#{i18n['billing.invoices.label']}" />
	</ui:define>

    <ui:define name="content">    
		<ui:include src="billingList.xhtml">
			<ui:param name="billingListController" value="#{billingInvoiceListController}"/>
		</ui:include>
	</ui:define>

</ui:composition>

src/main/webapp/pages/billing/invoiceView.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:h="http://java.sun.com/jsf/html"	
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/templates/default.xhtml">

	<ui:define name="title">
		<h:outputText value="#{i18n['billing.invoice.label']}" />
	</ui:define>

	<ui:define name="content">
		<f:metadata>
			<f:viewAction action="#{billingInvoiceViewController.init}"
				onPostback="false" />
		</f:metadata>
	
		<ui:include src="billingView.xhtml">
			<ui:param name="billingViewController"
				value="#{billingInvoiceViewController}" />
		</ui:include>
	</ui:define>

</ui:composition>